# 项目自定义配置
project:
  # 文件上传路径 (请修改为你电脑或服务器的实际路径)
  # Windows 示例: D:/campus-project/uploadPath
  # Linux 示例: /home/campus/uploadPath
  profile: "D:/Lambda/git_repo/CampusHelp/CampusHelpApi/uploadPath"

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_help?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456

    druid:
      aop-patterns: com.yqn.*
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin

      web-stat-filter:
        enabled: true
        url-pattern: /*
logging:
  level:
    com.yqn.mapper: debug
#    org.springframework.web: DEBUG